name: test-soci

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test_soci_action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install soci and test presence in path
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install soci
        uses: ./
      - name: Check install!
        run: soci --version
      - name: Check root directory
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi
        shell: bash

  test_soci_action_wrong:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Try to install a wrong soci
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install soci
        uses: ./
        with:
          soci-release: 'honk'
        continue-on-error: true

  test_soci_action_custom_dir:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install Custom soci and test presence in path
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install soci
        uses: ./
        with:
          install-dir: "$HOME/.socitest"
      - name: Check install!
        run: soci --version
      - name: Check install dir!
        run: |
          [[ $(dirname "$(which soci)") == "$HOME/.socitest" ]]
        shell: bash
      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_soci_action_custom_dir_root:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install Custom soci and test presence in path with custom root dir
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install soci
        uses: ./
        with:
          install-dir: /usr/bin
      - name: Check install!
        run: soci --version
      - name: Check install dir!
        run: |
          [[ $(dirname "$(which soci)") == /usr/bin ]]
        shell: bash
      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_soci_with_go_install:
    permissions: {}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go_version: ['1.19', '1.20']
    name: Try to install soci with go ${{ matrix.go_version }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
      - name: Install soci
        uses: ./
        with:
          soci-release: 'main'
      - name: Check install!
        run: soci --version